# Example Home Assistant REST Sensor 
# See https://www.home-assistant.io/integrations/sensor.rest#fetch-multiple-json-attributes-and-present-them-as-values for more information on how this works. 
# 

# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

rest:
  - resource: http://10.81.1.73/api/summary
    sensor:
      - name: "Pond"
        unique_id: "pico_pond"
        value_template:  "{{ value_json['avg_pond'] | round(1) }}"
        device_class: temperature
        unit_of_measurement: "°C"
      - name: "Housing"
        unique_id: "pico_housing"
        value_template:  "{{ value_json['housing'] | round(1) }}"
        device_class: temperature
        unit_of_measurement: "°C"
      - name: "Pico_Onboard"
        unique_id: "pico_onboard"
        value_template:  "{{ value_json['onboard'] | round(1) }}"
        device_class: temperature
        unit_of_measurement: "°C"
